name: wsgate
version: "1.2.0.444"
summary: FreeRDP WebConnect
description: A HTML5 gateway to FreeRDP
architectures:
  - amd64
confinement: strict
base: core18
apps:
  wsgate:
    command: usr/bin/wsgate
    plugs:
      - network
      - network-bind
grade: stable
parts:
  boost:
    plugin: nil
    source: https://dl.bintray.com/boostorg/release/1.63.0/source/boost_1_63_0.tar.gz
    stage-packages:
      - libicu60
    build-packages:
      - libssl1.0-dev
      - build-essential
      - debhelper
      - dpkg-dev
      - dctrl-tools
      - zlib1g-dev
      - libbz2-dev
      - libicu-dev
      - mpi-default-dev
      - bison
      - flex
      - docbook-to-man
      - help2man
      - xsltproc
      - doxygen
      - dh-python
      - g++
      - g++-5
      - python
      - python-all-dev
      - python3
      - python3-all-dev
    override-build: |
      ./bootstrap.sh --prefix=$SNAPCRAFT_PART_INSTALL/usr
      ./bjam install -j8
  freerdp:
    plugin: cmake
    after: [ boost]
    source: https://github.com/FreeRDP/FreeRDP
    source-type: git
    source-branch: stable-1.1
  ehs:
    plugin: cmake
    after: [boost]
    source: https://github.com/cloudbase/EHS.git
    source-type: git
    configflags:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCOMPILE_WITH_SSL=1"
    build-packages:
      - cmake
      - g++
      - pkg-config
      - zlib1g-dev
  cpprest:
    plugin: cmake
    source: https://github.com/microsoft/cpprestsdk.git
    source-type: git
  wsgate:
    plugin: cmake
    after: [ehs, freerdp, cpprest]
    source-subdir: wsgate
    source: .
    configflags:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
    build-packages:
      - pkg-config
      - libpng-dev
